version: "3"

services:
  docmost:
    user: 0:0
    image: docmost/docmost:${SOFTWARE_VERSION_TAG}
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "https://${DOMAIN}"
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
      REDIS_URL: "redis://redis:6379"
      STORAGE_DRIVER: ${STORAGE_DRIVER}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
    ports:
      - "172.17.0.1:41007:3000"
    restart: always
    volumes:
      - ./storage/docmost:/app/data/storage

  db:
    image: elestio/postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 172.17.0.1:59136:5432
    volumes:
      - ./storage/db_data:/var/lib/postgresql/data

  redis:
    image: elestio/redis:7.2
    restart: always
    volumes:
      - ./storage/redis_data:/data

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:24124:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
